### ISSUE TITLE
Phusit is always with you

### ISSUE THREAD

**Issue by hirasawaau** [Npwskp/Npwskp_github#1]
Try to say love phusit and toto in infinity loop

**Comment by hirasawaau** [comment]
Try to say love Phusit in infinity loop.

**Comment by Npwskp** [comment]
jai yen yen na ror pap

**Comment by Npwskp** [comment]
https://github.com/Npwskp/Npwskp_github/commit/1be51dbfbbd1945a37216cf2670297b722a0a97f
sed leaw

**Comment by Npwskp** [comment]
#2
